### ISSUE TITLE
Список Топ 20 депутатів фракції

### ISSUE THREAD

**Issue by beastie87** [OPORA/rada_stenograma#1]
В виводі [гупи](http://st.oporaua.org/groups/init?fraction=%D0%9E%D0%B1%E2%80%99%D1%94%D0%B4%D0%BD%D0%B0%D0%BD%D0%BD%D1%8F+%22%D0%A1%D0%B0%D0%BC%D0%BE%D0%BF%D0%BE%D0%BC%D1%96%D1%87%22&page=11&per=5#speeches) є топ 20 виступаючих депутатів 
![image](https://cloud.githubusercontent.com/assets/14181304/24238099/b95b85ac-0fb1-11e7-964e-4032545342f0.png) як саме вірно було б назвати цю частину?

**Comment by khorunzhiy** [comment]
я б назвав просто:

Депутати фракції Народний Фронт

**Comment by lisoffsky** [comment]
@khorunzhiy але вони там не всі. Тому Гена і пропонує Топ-20, щоб було зрозуміло. 

Як вам "ТОП-20 депутатів Народного фронту". Так як це ресурс про стенограми - буде зрозуміло, що найбільш балакучих топ-20

**Comment by khorunzhiy** [comment]
да "ТОП-20 депутатів Народного фронту" буде ок

**Comment by beastie87** [comment]
It is done
