### ISSUE TITLE
Інші партії в виводі стенограм Фракції

### ISSUE THREAD

**Issue by beastie87** [OPORA/rada_stenograma#2]
На сторінці Фракції  [ НАРОДНИЙ ФРОНТ ](http://st.oporaua.org/groups/init?fraction=%D0%A4%D1%80%D0%B0%D0%BA%D1%86%D1%96%D1%8F+%D0%9F%D0%BE%D0%BB%D1%96%D1%82%D0%B8%D1%87%D0%BD%D0%BE%D1%97+%D0%BF%D0%B0%D1%80%D1%82%D1%96%D1%97+%22%D0%9D%D0%90%D0%A0%D0%9E%D0%94%D0%9D%D0%98%D0%99+%D0%A4%D0%A0%D0%9E%D0%9D%D0%A2%22l) є розділ інші партії 
![image](https://cloud.githubusercontent.com/assets/14181304/24275879/7afa6e7e-103b-11e7-8692-2d808c0a675f.png)
 питання в тому чи потрібно в цьому розділі посилання на цю ж фракцію?

**Comment by lisoffsky** [comment]
думаю самим на себе лінка робити не треба

**Comment by beastie87** [comment]
@lisoffsky дякую, зроблено
