### ISSUE TITLE
Фракції

### ISSUE THREAD

**Issue by beastie87** [OPORA/rada_stenograma#3]
Вибрав по базі депутатів фракції, вийшло 11, скажіть чи вірне буде скорочення, та підскажіть будь ласка де можна знайти емблеми, помню що були на сайті https://rada.oporaua.org але не можу їх знайти( Дякую!
А ось і список:
```

1
party: "Позафракційні""
  short_name:  'Позафракційні'
  party_id: null
2
  party: "Фракція Політичної партії \"НАРОДНИЙ ФРОНТ\""
  short_name: 'Народний фронт'
  party_id: 2612
3
  party: "Фракція ПАРТІЇ \"БЛОК ПЕТРА ПОРОШЕНКА\""
  short_name: 'Блок Петра Порошенка'
  party_id: 2613
4
  party: "Фракція Політичної партії \"Об'єднання \"САМОПОМІЧ\""
  short_name: 'Об’єднання "Самопоміч"'
  party_id: 2614
5
  party: "Фракція Радикальної партії Олега Ляшка"
  short_name: 'Радикальна партія'
  party_id: 2615
6
  party: "Фракція Політичної партії \"Опозиційний блок\" у Верховній Раді України восьмого скликання"
  short_name: 'Опозиційний блок'
  party_id: 2616
7
  party: "Фракція політичної партії \"Всеукраїнське об'єднання \"Батьківщина\" у Верховній Раді України"
  short_name: 'ВО "Батьківщина"'
  party_id: 2617
8
  party: "Група \"Економічний розвиток\""
  short_name: 'Економічний розвиток"'
  party_id: 2618
9
  party: "Група \"Воля народу\""
  short_name: "Воля народу"
  party_id: 2619
10
  party: "Група \"Відродження\""
  short_name: "Відродження"
  party_id: 2795
11
  party: "Група \"Партія \"Відродження\""
  short_name: 'Партія "Відродження"'
  party_id: 2846

```

**Comment by almelnikova** [comment]
Економічний розвиток перейменувався у группу "Відродження", яка перейменувалась у группу "Партія "Відродження". Це одні і ті самі люди.

**Comment by almelnikova** [comment]
Лого БПП і Відродження у форматі пнг знаходила через Гугл, думаю, інші там теж є)

**Comment by lisoffsky** [comment]
@almelnikova співпадіння між ними не 100%

@beastie87 №8, №10 треба видалити. їх вже немає. Все інше чудово

**Comment by beastie87** [comment]
https://github.com/OPORA/rada_stenograma/issues/3#issuecomment-288983111 `> @beastie87 №8, №10 треба видалити. їх вже немає. Все інше чудово`
 
обговорили, так як партії не видаляються з евріполітішена і залишається пирвзязаність фаркційних переходів на rada4you, то вони залишаються для маркування вибувших депутатів та виступів депутатів, коли вони були в тій чи іншій фракції
