### ISSUE TITLE
відсутня сторінка чи повідомлення для випадку, коли пошук невдалий

### ISSUE THREAD

**Issue by GS-0001** [OPORA/rada_stenograma#6]
у випадку, коли користувач задає пошуковий запит і система нічого не знаходить, відсутнє "повідомлення" про це. можливі варіанти рішення:
- окремий екран про "невдалий" пошук з пропозиціями здійснити пошук ще раз, чи здійснити альтернативний пошук;
- повідомлення про "невдалий" пошук з пропозиціями здійснити пошук ще раз, чи здійснити альтернативний пошук

**Comment by lisoffsky** [comment]
давайте зробим "Ой, пошук не вдалий"

**Comment by beastie87** [comment]
зробив
