### ISSUE TITLE
некоректне відображення стенограм, неправдива інформація

### ISSUE THREAD

**Issue by almelnikova** [OPORA/rada_stenograma#9]
@beastie87 є така тєма. Я шукаю інфу, скільки разів депутати передають слово своїм колегам. За допомогою стенограм дивлюсь результати запитів "прошу передати слово", "передать слово", "передаю слово". Так от, у випадку "передаю слово" лідером таких "передавань" є Андрій Парубій (картіночка). Коли заходиш на профайл Парубія і обираєш "Виступи", то там нема жодного згадування "передаю слово" (картінок). Але разом з тим є купа дат виступів без розшифровок (фоточка є). Але коли переходиш по цим датам, то тебе посилає на стенограми на сайті Верховної Ради, де показує, що слово просить передати зовсім не Парубій, а якийсь депутат (картіночка). І так ціла купа дат. Виходячи з цього, Парубій зовсім не лідер по передачі слова, а значить на сайті неправдива інформація. 
![default](https://user-images.githubusercontent.com/26627527/27077332-5efcb460-5038-11e7-8fad-0e6e641c1755.JPG)
![1](https://user-images.githubusercontent.com/26627527/27077339-666e9c2c-5038-11e7-8e7c-705d07d556c1.JPG)
![2](https://user-images.githubusercontent.com/26627527/27077346-6a548c70-5038-11e7-8b4f-e2bfd9d482f3.JPG)
![3](https://user-images.githubusercontent.com/26627527/27077349-6dc1cb66-5038-11e7-8ced-6e181ccffc7a.JPG)

**Comment by beastie87** [comment]
http://st.oporaua.org/search/%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%8E%20%D1%81%D0%BB%D0%BE%D0%B2%D0%BE?page=17&per=5#speeches ось виступ Новак, в офісі поясню більш детально
